% read next event in the file. DO NOT RUN THIS SCRIPT.
[nextLine, nextTime, nextEvent,...
    nextNextTime,nextNextEvent, sample_File] = increment(nextLine, nextTime, nextEvent,...
    nextNextTime,nextNextEvent, sample_File);
